name: OpenCart build image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download OpenCart
        run: wget -O opencart.zip https://github.com/opencart/opencart/archive/refs/tags/4.1.0.3.zip

      - name: Extract OpenCart
        run: |
          unzip -q opencart.zip -d opencart
          shopt -s dotglob
          mv opencart/opencart-*/** opencart/
          rm -rf opencart/opencart-*/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push PHP Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/opencart:latest

      - name: Deploy (todo)
        run: echo "todo deploy"
